<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315083634 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Client entity, client_profile join table, and soft-delete fields on Profile';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN client.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404555E237E06 ON client (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404555F37A13B ON client (token)');
        $this->addSql('CREATE TABLE client_profile (client_id INT NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (client_id, profile_id))');
        $this->addSql('CREATE INDEX IDX_D36AEE7219EB6921 ON client_profile (client_id)');
        $this->addSql('CREATE INDEX IDX_D36AEE72CCFA12B8 ON client_profile (profile_id)');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT FK_D36AEE7219EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT FK_D36AEE72CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile ADD deleted BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE profile ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN profile.deleted_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_profile DROP CONSTRAINT FK_D36AEE7219EB6921');
        $this->addSql('ALTER TABLE client_profile DROP CONSTRAINT FK_D36AEE72CCFA12B8');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_profile');
        $this->addSql('ALTER TABLE profile DROP deleted');
        $this->addSql('ALTER TABLE profile DROP deleted_at');
    }
}
