<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519153030 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add profile_group table and profile_group_profile join table for client-scoped groups of profiles';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE profile_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A14DB1719EB6921 ON profile_group (client_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_group_client_name ON profile_group (client_id, name)');
        $this->addSql('CREATE TABLE profile_group_profile (group_id INT NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (group_id, profile_id))');
        $this->addSql('CREATE INDEX IDX_29545BC3FE54D947 ON profile_group_profile (group_id)');
        $this->addSql('CREATE INDEX IDX_29545BC3CCFA12B8 ON profile_group_profile (profile_id)');
        $this->addSql('ALTER TABLE profile_group ADD CONSTRAINT FK_9A14DB1719EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_group_profile ADD CONSTRAINT FK_29545BC3FE54D947 FOREIGN KEY (group_id) REFERENCES profile_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_group_profile ADD CONSTRAINT FK_29545BC3CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE profile_group DROP CONSTRAINT FK_9A14DB1719EB6921');
        $this->addSql('ALTER TABLE profile_group_profile DROP CONSTRAINT FK_29545BC3FE54D947');
        $this->addSql('ALTER TABLE profile_group_profile DROP CONSTRAINT FK_29545BC3CCFA12B8');
        $this->addSql('DROP TABLE profile_group');
        $this->addSql('DROP TABLE profile_group_profile');
    }
}
